openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - python_proficiency_level
                - ros2_experience
                - gpu_robotics_hardware_access
                - education_career_stage
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                python_proficiency_level:
                  type: string
                ros2_experience:
                  type: string
                gpu_robotics_hardware_access:
                  type: boolean
                education_career_stage:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input
  /auth/login:
    post:
      summary: Log in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: User logged in successfully
        '401':
          description: Invalid credentials
  /auth/me:
    get:
      summary: Get current user profile
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
                  python_proficiency_level:
                    type: string
                  ros2_experience:
                    type: string
                  gpu_robotics_hardware_access:
                    type: boolean
                  education_career_stage:
                    type: string
                  personalization_level:
                    type: string
        '401':
          description: Unauthorized
    put:
      summary: Update user profile preferences
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                python_proficiency_level:
                  type: string
                ros2_experience:
                  type: string
                gpu_robotics_hardware_access:
                  type: boolean
                education_career_stage:
                  type: string
                personalization_level:
                  type: string
      responses:
        '200':
          description: Profile updated successfully
        '401':
          description: Unauthorized
