openapi: 3.0.0
info:
  title: RAG Chatbot API
  version: 1.0.0
paths:
  /rag/query:
    post:
      summary: Send a query to the RAG chatbot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
                - chapter_context_id # Optional, to narrow down context
              properties:
                query:
                  type: string
                chapter_context_id:
                  type: string
                  nullable: true
      responses:
        '200':
          description: RAG chatbot response
          content:
            application/json:
              schema:
                type: object
                properties:
                  query:
                    type: string
                  response:
                    type: string
                  source_chunks:
                    type: array
                    items:
                      type: string
        '400':
          description: Invalid query
