openapi: 3.0.0
info:
  title: Translation API
  version: 1.0.0
paths:
  /translate/{chapter_id}:
    post:
      summary: Request Urdu translation for a chapter
      parameters:
        - in: path
          name: chapter_id
          schema:
            type: string
          required: true
          description: The ID of the chapter to translate
      responses:
        '200':
          description: Urdu translated chapter content
          content:
            application/json:
              schema:
                type: object
                properties:
                  chapter_id:
                    type: string
                  translated_content:
                    type: string
        '401':
          description: Unauthorized
        '404':
          description: Chapter not found
