@echo off
echo Starting RAG Chatbot Backend Server...
cd /d "%~dp0"
echo Activating virtual environment...
call venv\Scripts\activate.bat
echo Starting uvicorn server on port 8001...
python -m uvicorn app:app --host 0.0.0.0 --port 8001 --reload
pause
